# Generated by Django 2.1.7 on 2019-03-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordnet30',
            name='word',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wordnet30',
            name='pos',
            field=models.CharField(default='', max_length=5),
        ),
    ]
