# Generated by Django 2.1.7 on 2019-04-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0002_create_wordnet_copy_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField()),
                ('gloss_with_replacement', models.CharField(blank=True, max_length=255, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=255, null=True)),
                ('utterance_id', models.PositiveIntegerField()),
                ('transcript_id', models.PositiveIntegerField()),
                ('corpus_id', models.PositiveIntegerField()),
                ('collection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('requires_tags', models.BooleanField()),
            ],
            options={
                'db_table': 'derived_tokens',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('user_type', models.CharField(choices=[('mechenical_turk', 'Mechanical Turk Workers'), ('in_lab_staff', 'In-lab Trained Staff')], default='in_lab_staff', max_length=20)),
                ('browser_display_lang', models.CharField(blank=True, max_length=20, null=True)),
                ('browser_user_agent', models.TextField()),
                ('browser_platform', models.TextField()),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss_with_replacement', models.CharField(blank=True, max_length=255, null=True)),
                ('sense_offset', models.PositiveIntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ws_web.Participant')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ws_web.DerivedTokens')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('token', 'participant', 'sense_offset')},
        ),
    ]
