# Generated by Django 2.2 on 2019-06-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0005_auto_20190502_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance_ids', models.TextField()),
                ('transcript_id', models.PositiveIntegerField()),
                ('corpus_id', models.PositiveIntegerField()),
                ('collection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('idle', 'IDLE'), ('active', 'ACTIVE')], default='idle', max_length=20)),
                ('times_worked', models.PositiveIntegerField(default=0)),
                ('last_active_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'work_unit',
            },
        ),
        migrations.AddField(
            model_name='tags',
            name='fixed_pos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
