# Generated by Django 2.2 on 2019-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0006_auto_20190603_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='sense_offset',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
