# Generated by Django 2.2 on 2019-06-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0007_auto_20190603_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='transcript_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
