# Generated by Django 2.2 on 2019-06-24 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0010_auto_20190624_0339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workunitcontent',
            table='work_unit_content',
        ),
    ]
