# Generated by Django 2.2 on 2020-05-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0011_auto_20190624_0340'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='tags',
        #     name='timestamp',
        #     field=models.DateTimeField(null=True),
        # ),
        migrations.AlterField(
            model_name='participant',
            name='user_type',
            field=models.CharField(choices=[('mechanical_turk', 'Mechanical Turk Workers'), ('in_lab_staff', 'In-lab Trained Staff'), ('subject_pool', 'Subject Pool'), ('berkeley_ra_pool', 'Berkely RAs'), ('berkeley_rpp', 'Berkeley RPP')], default='in_lab_staff', max_length=20),
        ),
    ]
