# Generated by Django 2.2 on 2020-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0012_auto_20200526_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_type',
            field=models.CharField(choices=[('mechanical_turk', 'Mechanical Turk Workers'), ('in_lab_staff', 'In-lab Trained Staff'), ('subject_pool', 'Subject Pool'), ('berkeley_ra_pool', 'Berkely RAs'), ('berkeley_rpp', 'Berkeley RPP'), ('princeton_rpp', 'Princeton RPP')], default='in_lab_staff', max_length=20),
        ),
    ]
