# Generated by Django 2.2 on 2020-10-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_web', '0014_auto_20200926_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_type',
            field=models.CharField(choices=[('mechanical_turk', 'Mechanical Turk Workers'), ('in_lab_staff', 'In-lab Trained Staff'), ('subject_pool', 'Subject Pool'), ('berkeley_ra_pool', 'Berkely RAs'), ('berkeley_rpp', 'Berkeley RPP'), ('princeton_rpp', 'Princeton RPP'), ('edinburgh_two_hour_rpp', 'Edinburgh 2 Hour RPP'), ('berkeley_two_hour_rpp', 'Berkeley 2 Hour RPP')], default='in_lab_staff', max_length=50),
        ),
    ]
