# Generated by Django 2.1.7 on 2019-03-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordNet30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('examples', models.TextField()),
                ('lemma_names', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField()),
                ('pos', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'wordnet30',
            },
        ),
    ]
